parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: '3308'
    database_name: pi_dev
    database_user: root
    database_password: root
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: e6b97605dcc4d14101038f41410f9a2ffb125b0b
    database_path: null
